apiVersion: apps/v1
kind: Deployment
metadata:
  name: rfedccv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rfedccv
  template:
    metadata:
      labels:
        app: rfedccv
    spec:
      containers:
      - image: okteto.dev/rfedccv:latest
        name: rfedccv
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "45f2d1f2-6430-4136-a5e4-2537bdddd357"
        - name: Vless_Path
          value: "/vlyuijjm"
        - name: Vmess_UUID
          value: "45f2d1f2-6430-4136-a5e4-2537bdddd357"
        - name: Vmess_Path
          value: "/vmuknm666"
        - name: Share_Path
          value: "/v2link"
